// Generated by gencpp from file na_mapping/save_mapResponse.msg
// DO NOT EDIT!


#ifndef NA_MAPPING_MESSAGE_SAVE_MAPRESPONSE_H
#define NA_MAPPING_MESSAGE_SAVE_MAPRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace na_mapping
{
template <class ContainerAllocator>
struct save_mapResponse_
{
  typedef save_mapResponse_<ContainerAllocator> Type;

  save_mapResponse_()
    : success(false)  {
    }
  save_mapResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::na_mapping::save_mapResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::na_mapping::save_mapResponse_<ContainerAllocator> const> ConstPtr;

}; // struct save_mapResponse_

typedef ::na_mapping::save_mapResponse_<std::allocator<void> > save_mapResponse;

typedef boost::shared_ptr< ::na_mapping::save_mapResponse > save_mapResponsePtr;
typedef boost::shared_ptr< ::na_mapping::save_mapResponse const> save_mapResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::na_mapping::save_mapResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::na_mapping::save_mapResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::na_mapping::save_mapResponse_<ContainerAllocator1> & lhs, const ::na_mapping::save_mapResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::na_mapping::save_mapResponse_<ContainerAllocator1> & lhs, const ::na_mapping::save_mapResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace na_mapping

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::na_mapping::save_mapResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::na_mapping::save_mapResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::na_mapping::save_mapResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::na_mapping::save_mapResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::na_mapping::save_mapResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::na_mapping::save_mapResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::na_mapping::save_mapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::na_mapping::save_mapResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::na_mapping::save_mapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "na_mapping/save_mapResponse";
  }

  static const char* value(const ::na_mapping::save_mapResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::na_mapping::save_mapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::na_mapping::save_mapResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::na_mapping::save_mapResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct save_mapResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::na_mapping::save_mapResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::na_mapping::save_mapResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NA_MAPPING_MESSAGE_SAVE_MAPRESPONSE_H
