// Generated by gencpp from file na_mapping/save_map.msg
// DO NOT EDIT!


#ifndef NA_MAPPING_MESSAGE_SAVE_MAP_H
#define NA_MAPPING_MESSAGE_SAVE_MAP_H

#include <ros/service_traits.h>


#include <msg/save_mapRequest.h>
#include <msg/save_mapResponse.h>


namespace na_mapping
{

struct save_map
{

typedef save_mapRequest Request;
typedef save_mapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct save_map
} // namespace na_mapping


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::na_mapping::save_map > {
  static const char* value()
  {
    return "9b82c64d089149d300598523af304f22";
  }

  static const char* value(const ::na_mapping::save_map&) { return value(); }
};

template<>
struct DataType< ::na_mapping::save_map > {
  static const char* value()
  {
    return "na_mapping/save_map";
  }

  static const char* value(const ::na_mapping::save_map&) { return value(); }
};


// service_traits::MD5Sum< ::na_mapping::save_mapRequest> should match
// service_traits::MD5Sum< ::na_mapping::save_map >
template<>
struct MD5Sum< ::na_mapping::save_mapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::na_mapping::save_map >::value();
  }
  static const char* value(const ::na_mapping::save_mapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::na_mapping::save_mapRequest> should match
// service_traits::DataType< ::na_mapping::save_map >
template<>
struct DataType< ::na_mapping::save_mapRequest>
{
  static const char* value()
  {
    return DataType< ::na_mapping::save_map >::value();
  }
  static const char* value(const ::na_mapping::save_mapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::na_mapping::save_mapResponse> should match
// service_traits::MD5Sum< ::na_mapping::save_map >
template<>
struct MD5Sum< ::na_mapping::save_mapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::na_mapping::save_map >::value();
  }
  static const char* value(const ::na_mapping::save_mapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::na_mapping::save_mapResponse> should match
// service_traits::DataType< ::na_mapping::save_map >
template<>
struct DataType< ::na_mapping::save_mapResponse>
{
  static const char* value()
  {
    return DataType< ::na_mapping::save_map >::value();
  }
  static const char* value(const ::na_mapping::save_mapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NA_MAPPING_MESSAGE_SAVE_MAP_H
